# Diabetes Prediction Project

In [5]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [6]:
df = pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [7]:
df.shape # 768 rows and 9 columns

(768, 9)

In [4]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [8]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

# 0 - non diabetic
# 1 - diabetic

In [9]:
# drop the outcome column, 

x = df.drop(columns = 'Outcome' , axis =1)
y = df['Outcome']

In [10]:
x # without outcome

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [11]:
y # outcome

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [12]:
scaler = StandardScaler()

In [13]:
scaler.fit(x)

StandardScaler()

In [14]:
standardized_data = scaler.transform(x)

In [15]:
standardized_data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [16]:
x = standardized_data

In [17]:
x # final x

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [18]:
y # final y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

# training and testing part

In [19]:
x_train, x_test, y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [20]:
x_train.shape # 80% 

(614, 8)

In [21]:
x_test.shape # 20% for testing(0.2)

(154, 8)

# Check the accuracy of train and test model

In [22]:
# classification problem to find the person who has diabetes or not
clf = svm.SVC(kernel='linear')

In [23]:
clf.fit(x_train,y_train)

SVC(kernel='linear')

In [24]:
# accuracy for the training data

x_train_prediction = clf.predict(x_train)
accuracy_score(x_train_prediction,y_train)

0.8029315960912052

In [25]:
# accuracy of the test data

x_test_prediction = clf.predict(x_test)
accuracy_score(x_test_prediction,y_test)

0.7272727272727273

In [26]:
# based on the features predict person has or not
# input data for the 8 columns for a random person


input_sample = (0.5,100,55,14,33.5,5,9,56)

In [27]:
input_np_array = np.asarray(input_sample)

In [28]:
input_np_array_reshaped = input_np_array.reshape(1,-1)

In [29]:
# standardize the input data

std_data = scaler.transform(input_np_array_reshaped)

C:\Users\My-PC\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [30]:
std_data

array([[-0.99336828, -0.65393918, -0.729221  , -0.41001936, -0.40201356,
        -3.42587765, 25.75594566,  1.93652192]])

In [31]:
prediction = clf.predict(std_data)
prediction  # prediction is 1 , it means person is diabetes

array([1], dtype=int64)

In [32]:
if (prediction[0]==0):
    print("Person does not suffer from diabetic")
else:
    print("Person suffers from diabetic")

Person suffers from diabetic


In [16]:
import ipywidgets as widgets
from IPython.display import display
import numpy as np  # You need to import NumPy for array manipulation
from IPython.display import clear_output

# Assuming you have a trained model named `model` for predicting diabetes
# Make sure you have defined the predict_diabetes function using this model

# Define a function to predict diabetes based on input features
def predict_diabetes(features):
    # Your prediction logic here using your trained model
    # For demonstration, let's assume it's a simple threshold-based prediction
    threshold = 0.5  # You may adjust the threshold as per your model's requirements
    prediction = np.where(features > threshold, 1, 0)
    return prediction

# Create input widgets for sample data
pregnancies_input = widgets.IntSlider(description='Pregnancies:', min=0, max=17, value=0)
glucose_input = widgets.IntSlider(description='Glucose:', min=0, max=200, value=100)
blood_pressure_input = widgets.IntSlider(description='Blood Pressure:', min=0, max=122, value=72)
skin_thickness_input = widgets.IntSlider(description='Skin Thickness:', min=0, max=99, value=23)
insulin_input = widgets.IntSlider(description='Insulin:', min=0, max=846, value=79)
bmi_input = widgets.FloatSlider(description='BMI:', min=0, max=67, value=32.0)
dpf_input = widgets.FloatSlider(description='Diabetes Pedigree Function:', min=0.0, max=2.42, value=0.3725)
age_input = widgets.IntSlider(description='Age:', min=21, max=81, value=29)

# Define a function to handle prediction when the button is clicked
def on_button_clicked(b):
    clear_output(wait=True)  # Clear the output area, wait=True ensures that the output is cleared immediately
    features = [
        pregnancies_input.value,
        glucose_input.value,
        blood_pressure_input.value,
        skin_thickness_input.value,
        insulin_input.value,
        bmi_input.value,
        dpf_input.value,
        age_input.value
    ]
    prediction = predict_diabetes(np.array(features))  # Use your predict_diabetes function
    if prediction[0] == 0:
        print("The person does not have diabetes.")
    else:
        print("The person has diabetes.")
        
# Create a button widget
button = widgets.Button(description="Predict")

# Attach the button click event to the function
button.on_click(on_button_clicked)

# Display the widgets
display(
    pregnancies_input,
    glucose_input,
    blood_pressure_input,
    skin_thickness_input,
    insulin_input,
    bmi_input,
    dpf_input,
    age_input,
    button
)


IntSlider(value=0, description='Pregnancies:', max=17)

IntSlider(value=100, description='Glucose:', max=200)

IntSlider(value=72, description='Blood Pressure:', max=122)

IntSlider(value=23, description='Skin Thickness:', max=99)

IntSlider(value=79, description='Insulin:', max=846)

FloatSlider(value=32.0, description='BMI:', max=67.0)

FloatSlider(value=0.3725, description='Diabetes Pedigree Function:', max=2.42)

IntSlider(value=29, description='Age:', max=81, min=21)

Button(description='Predict', style=ButtonStyle())